### ISSUE TITLE
Upload Error - Product Group Feedback

### ISSUE THREAD

**Issue by LanceMcCarthy** [LanceMcCarthy/MvpApi#83]
If you select **Product Group Feedback** as the `ContributionType`, and POST it to the `https://mvpapi.azure-api.net/mvp/api/contributions?` endpoint, the API returns a 200 response. 

However, the response is HTML, not JSON data, and the activity is never added to the MVP's activities history.

Thus, the response cannot be deserialized properly and throws an expected Json.NET exception:
```
Object reference not set to an instance of an object.
```

**Comment by LanceMcCarthy** [comment]
This is a Json.NET deserialization problem. The contribution does successfully upload to the MVP's activities list.

```SubmitContributionAsync Exception: Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at MvpApi.Services.Apis.MvpApiService.<SubmitContributionAsync>d__12.MoveNext()
```

**Comment by LanceMcCarthy** [comment]
Updating the thread - the API team has been notified and are working on it.
